baseURL = "https://puneethkosaraju.com/"
languageCode = "en-us"
title = "Puneeth Kosaraju"
theme = "bilberry-hugo-theme"

enableRobotsTXT = true

# Change to your content language. Supported values: en, de, es, fr, ru
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
disqusShortname = "bilberry-hugo-theme"

Copyright = "Sample Copyright"

[params]
  # Favicon for the browser's favorites and tabs
  favicon = "" # set a favicon icon

  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = ["css/foo.css"]
  js_modules = []

  AuthorName = "Jon Doe"

  # Description and meta data for the search engines
  author = "kosarp"
  description = "My corner in the world wide web."
  keywords = "blog, personal, programming, snippets, coding"

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = true

  # Enable / Disable algolia search
  algolia_search    = false
  algolia_appId     = ""
  algolia_apiKey    = ""
  algolia_indexName = "default-content"

  # Header configuration
  # your subtitle if you want to use any
  subtitle = "A library of code snippets"

  # if you want to use gravatar for the header image
  gravatarEMail = ""

  # set an path to the image file you want to use | overwrites gravatar
  customImage = ""

  # always display the top navigation (with pages and search) on non-mobile screens
  permanentTopNav = true

  # social media profile urls for the footer links
  facebook   = ""
  twitter    = "https://twitter.com/indianethic"
  googleplus = ""
  pinterest  = ""
  instagram  = ""
  tumblr     = ""
  youtube    = ""
  vimeo      = ""
  github     = "https://github.com/puneethkosaraju"
  xing       = ""
  linkedin   = ""

# don't change anything here
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON" ]
  page = [ "HTML" ]
