baseURL = "https://puneethkosaraju.com/"
languageCode = "en-us"
title = "Puneeth Kosaraju"
theme = "hugo-theme-cactus-plus"

googleAnalytics = "your_google_analytics_id"

# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

[params]
	author = "Puneeth kosaraju"
	description = "puneethkosaraju.com Site Description"
	bio = "full stack developer &middot; sci-fi junkie &middot; blogger"

	twitter = "indianethic"
	facebook = "puneeth.kosaraju"

	enableRSS = true
	enableToc = true

	enableDisqus = true
	disqusShortname = "puneethkosaraju"

	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false

	enableGoogleAnalytics = false
	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = ''

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""

[params.Links]
	Projects = "/projects"

# Add additional social link entries underneath
[social]
	facebook-square = "https://www.facebook.com/puneeth.kosaraju"
	twitter-square = "https://www.twitter.com/indianethic"
	github-square = "https://www.github.com/puneethkosaraju"
